### ISSUE TITLE
create collection in labcam: collection not activated for automatic upload by default

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#105]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.

Actions: 
admin qa-imeji -> create new user

Log in new user-> message: there is no collection available, create one by giving a name-> ok ->"menue" 

Observation:
-> automatic upload activated and collection displayed in grey 

Expected result: Automatic upload not activated by default

**Comment by cafefish** [comment]
done

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 11.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Result: nok. Still reproducible: Automatic upload activated by default
