### ISSUE TITLE
Delete content of text note does not delete "text note" symbol of item in "local"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#107]
Testserver: gluons.mpdl.mpg.de
Test date: 11.05.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: hofmann@mpdl.mpg.de

Action: clear content of text note in item

-> create text note for item -> save -> edit textnote: delete all content -> save
-> tab "local" -> text note symbol is still displayed for item

Expected result: symbol deleted as soon as there is no contet available anymore

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: hofmann@mpdl.mpg.de

Test result: nok. still reproducible

**Comment by cafefish** [comment]
done

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 11.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user
Test result: nok. still reproducible, text noe icon displayed in item although no content available

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 1
1.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Actions: 

select 4 items -> add a text note for all -> select one item -> delete text -> save -> unfortunately. Labcam has stopped

Observation: coming back to "local", the text note labels for the other items are deleted, and the item where I deleted the content remained. 

Expected result: no App breakdown and only the lable of the actually deleted text note is deleted. The others should remain untouched.

**Comment by melissaMPDL** [comment]
Test for Bug #107
Action:	
•	Select several items
•	create note for all selected items
•	all items are labeled with note symbol
•	select one item with note symbol 
•	try to delete content of note

Observation: 
•	cannot save note without content 
•	clicking save button multiple times will most likely lead to the situation of the bar disappearing 
•	tapping in the region of the note bar with the text entry field or save/cancel bar area will make the bar visible again (even after leaving the picture and return to the front page)
•	no warning of the save button not working without content will seem like a delay in processing, and you will most likely push the button a few times. 
•	Entering a new name for the image seems not to work with the save button

Expectation: 
•	It should be possible to delete a single given note (not in form of deleting content though) and without using the manager (single choice is not given there and I could not find the option for deleting, voice notes can be deleted directly on the image, text notes not as it seems)
•	When renaming a note and pressing the save button, the keyboard should disappear 
•	user should know, that he left the text entry field open and the save process is not completed without a name
